modLoader="javafml"
loaderVersion="[43,)"
license="Apache License version 2.0"

[[mods]]
modId="engies_chaos"
version="25.56.58"
displayName="Engie's Chaos"
updateJSONURL="https://raw.githubusercontent.com/DevEngieGames/EngiesChaos-and-EngieLib/refs/heads/Update-Check/EngiesChaos.json"
displayURL="https://github.com/DevEngieGames/EngiesChaos-and-EngieLib"
logoFile="logo.png"
credits="DevEngie (All About Engie Creator)"
authors="EngieGames(aka xEngieGames/xEngie)"
description="A Reworked version of All About Engie by EngieGames with full permission from DevEngie to reupload All About Engie. If you find issues, report them on the GitHub page for the mod please and thank you."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.engies_chaos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.engies_chaos]]
    modId="engielib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"



# Start of user code block dependencies configuration
# End of user code block dependencies configuration